version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bitpin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    environment:
      POSTGRES_DB: bitpin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_POST: 5432
      BITPIN_SECRET_KEY: "dfnwefn223423rnewfw"
    ports:
      - "8000:8000"
    depends_on:
      - db
